import { Styles, Mapping, FilterLayerKeys } from '@/app/types'

interface StyleMapping extends Mapping {
  filterLayers: FilterLayerKeys[]
}

type StyleMap = { [K in Styles]: StyleMapping }

export const stylesMap: StyleMap = {
  Solitaire: {
    label: 'Solitaires',
    slug: 'solitaire',
    image: '/img/01_solitaires.png',
    filterLayers: ['pa_shape', 'pa_diamond-quality', 'pa_total-carat'],
    index: 0,
    display: true,
  },
  Halo: {
    label: 'Halos',
    slug: 'halo',
    image: '/img/02_halos.png',
    filterLayers: ['pa_shape', 'pa_diamond-quality', 'pa_centre-carat'],
    index: 1,
    display: true,
  },
  Cluster: {
    label: 'Clusters',
    slug: 'cluster',
    image: '/img/03_clusters.png',
    filterLayers: ['pa_diamond-quality', 'pa_total-carat'],
    index: 2,
    display: true,
  },
  'Three Stone': {
    label: '3-Stones',
    slug: '3-stone',
    image: '/img/04_3-stones.png',
    filterLayers: ['pa_shape', 'pa_diamond-quality', 'pa_centre-carat'],
    index: 3,
    display: false,
  },
  Trilogy: {
    label: '3-Stones',
    slug: '3-stone',
    image: '/img/04_3-stones.png',
    filterLayers: ['pa_shape', 'pa_diamond-quality', 'pa_centre-carat'],
    index: 3,
    display: true,
  },
  PLAIN: {
    label: 'Plains',
    slug: 'plains',
    image: '/img/05_plains.png',
    filterLayers: ['pa_profile', 'pa_gauge', 'pa_width'],
    index: 4,
    display: true,
  },
  Patterns: {
    label: 'Patterns',
    slug: 'patterns',
    image: '/img/06_patterns.png',
    filterLayers: ['pa_pattern', 'pa_gauge', 'pa_width'],
    index: 5,
    display: true,
  },
  'Two Colour': {
    label: '2-Colour',
    slug: '2-colour',
    image: '/img/07_2-colour.png',
    filterLayers: ['pa_pattern', 'pa_gauge', 'pa_width'],
    index: 6,
    display: true,
  },
  CERAMIC: {
    label: 'Ceramic',
    slug: 'ceramic',
    image: '/img/08_ceramic.png',
    filterLayers: ['pa_ceramic-colour', 'pa_width'],
    index: 7,
    display: true,
  },
  Shaped: {
    label: 'Shaped',
    slug: 'shaped',
    image: '/img/09_shaped.png',
    filterLayers: ['pa_diamond-set', 'pa_shape', 'pa_total-carat'],
    index: 8,
    display: true,
  },
  Diamond: {
    label: 'Diamond',
    slug: 'diamond',
    image: '/img/10_diamond.png',
    filterLayers: ['pa_shape', 'pa_setting', 'pa_total-carat'],
    index: 9,
    display: true,
  },
  'HALF SET': {
    label: 'Half set',
    slug: 'half-set',
    image: '/img/11_half-set.png',
    filterLayers: [
      'pa_shape',
      'pa_setting',
      'pa_diamond-quality',
      'pa_total-carat',
    ],
    index: 10,
    display: true,
  },
  'FULL SET': {
    label: 'Full set',
    slug: 'full-set',
    image: '/img/12_full-set.png',
    filterLayers: [
      'pa_shape',
      'pa_setting',
      'pa_diamond-quality',
      'pa_total-carat',
    ],
    index: 11,
    display: true,
  },
  'DRESS RING': {
    label: 'Dress',
    slug: 'dress',
    image: '/img/13_dress.png',
    filterLayers: ['pa_coverage', 'pa_shape', 'pa_setting'],
    index: 12,
    display: true,
  },
  EARRING: {
    label: 'Earrings',
    slug: 'earring',
    image: '/img/14_earrings.png',
    filterLayers: ['pa_shape', 'pa_diamond-quality', 'pa_total-carat'],
    index: 13,
    display: true,
  },
  PENDANT: {
    label: 'Pendants',
    slug: 'pendant',
    image: '/img/15_pendants.png',
    filterLayers: ['pa_shape', 'pa_diamond-quality', 'pa_total-carat'],
    index: 14,
    display: true,
  },
  BRACELET: {
    label: 'Bracelets',
    slug: 'bracelet',
    image: '/img/16_bracelets.png',
    filterLayers: ['pa_shape', 'pa_diamond-quality', 'pa_total-carat'],
    index: 15,
    display: true,
  },
  'Five Stone': {
    label: '5-Stones',
    slug: '5-stone',
    image: '/img/04_3-stones.png',
    filterLayers: ['pa_shape', 'pa_diamond-quality', 'pa_centre-carat'],
    index: 16,
    display: false,
  },
  Other: {
    label: 'Others',
    slug: 'other',
    image: '/img/04_3-stones.png',
    filterLayers: ['pa_shape', 'pa_diamond-quality', 'pa_centre-carat'],
    index: 18,
    display: false,
  },

  CELTIC: {
    label: 'Celtic',
    slug: 'celtic',
    filterLayers: ['pa_gauge', 'pa_width'],
    index: 19,
    display: false,
  },
  CONTEMPORARY: {
    label: 'Contemporary',
    slug: 'contemporary',
    filterLayers: ['pa_gauge', 'pa_width'],
    index: 20,
    display: false,
  },
  SPARKLE: {
    label: 'Sparkle',
    slug: 'sparkle',
    filterLayers: ['pa_gauge', 'pa_width'],
    index: 21,
    display: false,
  },
  'MIXED METAL': {
    label: 'Mixed Metal',
    slug: 'mixed-metal',
    filterLayers: ['pa_gauge', 'pa_width'],
    index: 22,
    display: false,
  },
  TRINITY: {
    label: 'Trinity',
    slug: 'trinity',
    filterLayers: ['pa_gauge', 'pa_width'],
    index: 23,
    display: false,
  },
}
