export type Styles =
  | 'SOLITAIRE'
  | 'HALO'
  | 'CLUSTER'
  | 'THREE STONE'
  | 'FIVE STONE'
  | 'TRILOGY'
  | 'Other'
  | 'BRACELET'
  | 'EARRING'
  | 'PENDANT'
  | 'DRESS RING'
  | 'FULL SET'
  | 'HALF SET'
  | 'Shaped'
  | 'PLAIN'
  | 'Patterns'
  | 'Diamond'
  | 'Two Colour'
  | 'CELTIC'
  | 'CERAMIC'
  | 'CONTEMPORARY'
  | 'SPARKLE'
  | 'MIXED METAL'
  | 'TRINITY'
