export type Styles =
  | 'Solitaire'
  | 'Halo'
  | 'Cluster'
  | 'Three Stone'
  | 'Five Stone'
  | 'Trilogy'
  | 'Other'
  | 'BRACELET'
  | 'EARRING'
  | 'PENDANT'
  | 'DRESS RING'
  | 'FULL SET'
  | 'HALF SET'
  | 'Shaped'
  | 'PLAIN'
  | 'Patterns'
  | 'Diamond'
  | 'Two Colour'
  | 'CELTIC'
  | 'CERAMIC'
  | 'CONTEMPORARY'
  | 'SPARKLE'
  | 'MIXED METAL'
  | 'TRINITY'
